const newdata = [
  {
    id: 'new_01',
    image: process.env.PUBLIC_URL+'/images/new_01.jpg',
    condition: '신상품',
    title: '조던',
    desc: '남성 긴팔 크루넥',
    color: '1개 색상',
    price: 45000,
    discount: 0.2,
  },
  {
    id: 'new_02',
    image: process.env.PUBLIC_URL+'/images/new_02.jpg',
    condition: '신상품',
    title: '에어 조던 1 로우 G',
    desc: '골프화',
    color: '3개 색상',
    price: 179000,
    discount: 0,
  },
  {
    id: 'new_03',
    image: process.env.PUBLIC_URL+'/images/new_03.jpg',
    condition: '신상품',
    title: '에어 조던 1 로우 SE',
    desc: '주니어 신발',
    color: '1개 색상',
    price: 139000,
    discount: 0,
  },
  {
    id: 'new_04',
    image: process.env.PUBLIC_URL+'/images/new_04.jpg',
    condition: '',
    title: '조던 에센셜',
    desc: '남성 스트레이트먼트 플리스 팬츠',
    color: '1개 색상',
    price: 105000,
    discount: 0,
  },
  {
    id: 'new_05',
    image: process.env.PUBLIC_URL+'/images/new_05.jpg',
    condition: '',
    title: '에어 조던 XXXVII 로우 PF',
    desc: '남성 농구화',
    color: '1개 색상',
    price: 209000,
    discount: 0,
  },
  {
    id: 'new_06',
    image: process.env.PUBLIC_URL+'/images/new_06.jpg',
    condition: '',
    title: '에어 조던 1 줌 컴포트 2',
    desc: '남성 신발',
    color: '1개 색상',
    price: 179000,
    discount: 0,
  },
  {
    id: 'new_07',
    image: process.env.PUBLIC_URL+'/images/new_07.jpg',
    condition: '친환경 소재',
    title: '조던 23 엔지니어드',
    desc: '남성 플리스 팬츠',
    color: '1개 색상',
    price: 139000,
    discount: 0,
  },
  {
    id: 'new_08',
    image: process.env.PUBLIC_URL+'/images/new_08.jpg',
    condition: '',
    title: '조던 에센셜',
    desc: '남성 플리스 팬츠',
    color: '1개 색상',
    price: 85000,
    discount: 0.1,
  },
  {
    id: 'new_09',
    image: process.env.PUBLIC_URL+'/images/new_09.jpg',
    condition: '',
    title: '조던 플라이트 MVP',
    desc: '남성 플리스 팬츠',
    color: '2개 색상',
    price: 85000,
    discount: 0,
  },
  {
    id: 'new_10',
    image: process.env.PUBLIC_URL+'/images/new_10.jpg',
    condition: '신상품',
    title: '조던 에센셜',
    desc: '여성 유틸리티 팬츠',
    color: '1개 색상',
    price: 119000,
    discount: 0.35,
  },
  {
    id: 'new_11',
    image: process.env.PUBLIC_URL+'/images/new_11.jpg',
    condition: '신상품',
    title: '조던 1 로우 알트 SE',
    desc: '베이비 신발',
    color: '1개 색상',
    price: 79000,
    discount: 0,
  },
  {
    id: 'new_12',
    image: process.env.PUBLIC_URL+'/images/new_12.jpg',
    condition: '신상품',
    title: '조던 플라이트',
    desc: '여성 자카드 니트 카디건',
    color: '1개 색상',
    price: 139000,
    discount: 0,
  },
  {
    id: 'new_13',
    image: process.env.PUBLIC_URL+'/images/new_13.jpg',
    condition: '신상품',
    title: '조던 Why Not?',
    desc: '남성 팬츠',
    color: '1개 색상',
    price: 99000,
    discount: 0,
  },
  {
    id: 'new_14',
    image: process.env.PUBLIC_URL+'/images/new_14.jpg',
    condition: '',
    title: '에어 조던 1 로우 SE',
    desc: '여성 신발',
    color: '1개 색상',
    price: 139000,
    discount: 0,
  },
  {
    id: 'new_15',
    image: process.env.PUBLIC_URL+'/images/new_15.jpg',
    condition: '신상품',
    title: '조던 에센셜',
    desc: '남성 웜업 재킷',
    color: '1개 색상',
    price: 139000,
    discount: 0,
  },
  {
    id: 'new_16',
    image: process.env.PUBLIC_URL+'/images/new_16.jpg',
    condition: '',
    title: '조던 브루클린',
    desc: '여성 플리스 팬츠',
    color: '2개 색상',
    price: 85000,
    discount: 0.2,
  },
  {
    id: 'new_17',
    image: process.env.PUBLIC_URL+'/images/new_17.jpg',
    condition: '친환경 소재',
    title: '조던 23 엔지니어드',
    desc: '남성 재킷',
    color: '1개 색상',
    price: 129000,
    discount: 0,
  },
  {
    id: 'new_18',
    image: process.env.PUBLIC_URL+'/images/new_18.jpg',
    condition: '신상품',
    title: '조던 23 엔지니어드',
    desc: '남성 플리스 팬츠',
    color: '2개 색상',
    price: 89000,
    discount: 0,
  },
  {
    id: 'new_19',
    image: process.env.PUBLIC_URL+'/images/new_19.jpg',
    condition: '신상품',
    title: '조던 에센셜',
    desc: '남성 레니게이드 재킷',
    color: '1개 색상',
    price: 289000,
    discount: 0,
  },
  {
    id: 'new_20',
    image: process.env.PUBLIC_URL+'/images/new_20.jpg',
    condition: '',
    title: '조던 플라이트 에센셜',
    desc: '남성용 오버사이즈 티셔츠',
    color: '1개 색상',
    price: 55000,
    discount: 0,
  },
  {
    id: 'new_21',
    image: process.env.PUBLIC_URL+'/images/new_21.jpg',
    condition: '신상품',
    title: '조던 플라이트',
    desc: '여성 벨루어 재킷',
    color: '2개 색상',
    price: 129000,
    discount: 0.1,
  },
  {
    id: 'new_22',
    image: process.env.PUBLIC_URL+'/images/new_22.jpg',
    condition: '신상품',
    title: '조던 드라이 핏 스포츠',
    desc: '남성 팬츠',
    color: '2개 색상',
    price: 105000,
    discount: 0,
  },
  {
    id: 'new_23',
    image: process.env.PUBLIC_URL+'/images/new_23.jpg',
    condition: '',
    title: '자이언 2 PF',
    desc: '남성 농구화',
    color: '1개 색상',
    price: 139000,
    discount: 0,
  },
  {
    id: 'new_24',
    image: process.env.PUBLIC_URL+'/images/new_24.jpg',
    condition: '',
    title: '에어 조던 XXXVII PF',
    desc: '남성 농구화',
    color: '1개 색상',
    price: 219000,
    discount: 0.2,
  },
  {
    id: 'new_25',
    image: process.env.PUBLIC_URL+'/images/new_25.jpg',
    condition: '신상품',
    title: '조던 23 엔지니어드',
    desc: '남성 재킷',
    color: '1개 색상',
    price: 129000,
    discount: 0.3,
  },
  {
    id: 'new_26',
    image: process.env.PUBLIC_URL+'/images/new_26.jpg',
    condition: '친환경 소재',
    title: '조던 23 엔지니어드',
    desc: '남성 플리스 풀오버',
    color: '2개 색상',
    price: 169000,
    discount: 0,
  },
  {
    id: 'new_27',
    image: process.env.PUBLIC_URL+'/images/new_27.jpg',
    condition: '',
    title: '조던 플라이트',
    desc: '여성 탑',
    color: '2개 색상',
    price: 59000,
    discount: 0,
  },
  {
    id: 'new_28',
    image: process.env.PUBLIC_URL+'/images/new_28.jpg',
    condition: '',
    title: '조던 에센셜',
    desc: '홀리데이 점프맨 플리스 풀오버',
    color: '2개 색상',
    price: 99000,
    discount: 0,
  },
  {
    id: 'new_29',
    image: process.env.PUBLIC_URL+'/images/new_29.jpg',
    condition: '',
    title: '조던 스포츠',
    desc: '여성 조거',
    color: '1개 색상',
    price: 85000,
    discount: 0.1,
  },
  {
    id: 'new_30',
    image: process.env.PUBLIC_URL+'/images/new_30.jpg',
    condition: '',
    title: '루카 1 PF',
    desc: '남성 농구화',
    color: '1개 색상',
    price: 129000,
    discount: 0,
  },
  {
    id: 'new_31',
    image: process.env.PUBLIC_URL+'/images/new_31.jpg',
    condition: '',
    title: '조던 플라이트',
    desc: '여성 벨루어 팬츠',
    color: '1개 색상',
    price: 109000,
    discount: 0,
  },
  {
    id: 'new_32',
    image: process.env.PUBLIC_URL+'/images/new_32.jpg',
    condition: '',
    title: '조던 플라이트 헤리티지 85',
    desc: '남성 크루',
    color: '1개 색상',
    price: 59000,
    discount: 0,
  },
  {
    id: 'new_33',
    image: process.env.PUBLIC_URL+'/images/new_33.jpg',
    condition: '',
    title: '조던 그랑빌 프로',
    desc: '남성 신발',
    color: '1개 색상',
    price: 159000,
    discount: 0,
  },
  {
    id: 'new_34',
    image: process.env.PUBLIC_URL+'/images/new_34.jpg',
    condition: '',
    title: '조던 플라이트',
    desc: '여성 플리스 팬츠',
    color: '2개 색상',
    price: 99000,
    discount: 0,
  },
  {
    id: 'new_35',
    image: process.env.PUBLIC_URL+'/images/new_35.jpg',
    condition: '',
    title: '조던 플라이트 시카고',
    desc: '여성 팬츠',
    color: '2개 색상',
    price: 149000,
    discount: 0,
  },
  {
    id: 'new_36',
    image: process.env.PUBLIC_URL+'/images/new_36.jpg',
    condition: '',
    title: '조던 플라이트 MVP',
    desc: '남성 그래픽 플리스 크루넥 스웻셔츠',
    color: '2개 색상',
    price: 89000,
    discount: 0,
  },
  {
    id: 'new_37',
    image: process.env.PUBLIC_URL+'/images/new_37.jpg',
    condition: '',
    title: '조던 플라이트 MVP 85',
    desc: '남성 긴팔 티셔츠',
    color: '1개 색상',
    price: 69000,
    discount: 0,
  },
  {
    id: 'new_38',
    image: process.env.PUBLIC_URL+'/images/new_38.jpg',
    condition: '',
    title: '조던',
    desc: '여성 우븐 팬츠',
    color: '1개 색상',
    price: 95000,
    discount: 0.3,
  },
  {
    id: 'new_39',
    image: process.env.PUBLIC_URL+'/images/new_39.jpg',
    condition: '',
    title: '조던 1 로우 알트',
    desc: '베이비 신발',
    color: '1개 색상',
    price: 69000,
    discount: 0,
  },
  {
    id: 'new_40',
    image: process.env.PUBLIC_URL+'/images/new_40.jpg',
    condition: '',
    title: '조던',
    desc: '여성 긴팔 벨루어 탑',
    color: '1개 색상',
    price: 85000,
    discount: 0.2,
  },
]

export default newdata