const prodata = [
  {
    id: 'pro_01',
    image: process.env.PUBLIC_URL+'/images/1.jpg',
    title: '조던 누 레트로 1 로우',
    desc: '남성 신발',
    color: '1개 색상',
    price: 129000,
    discount: 0,
    condition: '',
    type01: 'men',
    type02: 'snkrs',
    type03: 'retro',
  },
  {
    id: 'pro_02',
    image: process.env.PUBLIC_URL+'/images/2.jpg',
    title: '에어 조던 2 엘리베이트 로우',
    desc: '여성 신발',
    color: '2개 색상',
    price: 159000,
    discount: 0.1,
    condition: '',
    type01: 'women',
    type02: 'snkrs',
  },
  {
    id: 'pro_03',
    image: process.env.PUBLIC_URL+'/images/3.jpg',
    title: '조던',
    desc: '남성 긴팔 크루넥',
    color: '2개 색상',
    price: 45000,
    discount: 0.2,
    condition: '신상품',
    type01: 'men',
    type02: 'top',
  },
  {
    id: 'pro_04',
    image: process.env.PUBLIC_URL+'/images/4.jpg',
    title: '조던',
    desc: '남성 풀오버 후디',
    color: '1개 색상',
    price: 89000,
    discount: 0.2,
    condition: '',
    type01: 'men',
    type02: 'top',
  },
  {
    id: 'pro_05',
    image: process.env.PUBLIC_URL+'/images/5.jpg',
    title: '에어 조던 1 로우 SE',
    desc: '주니어 신발',
    color: '1개 색상',
    price: 139000,
    discount: 0,
    condition: '신상품',
    type01: 'junior',
    type02: 'snkrs',
  },
  {
    id: 'pro_06',
    image: process.env.PUBLIC_URL+'/images/6.jpg',
    title: '에어 조던 1 로우 G',
    desc: '골프화',
    color: '5개 색상',
    price: 179000,
    discount: 0,
    condition: '신상품',
    type01: 'genderless',
    type02: 'snkrs',
  },
  {
    id: 'pro_07',
    image: process.env.PUBLIC_URL+'/images/7.jpg',
    title: '에어 조던 6 레트로',
    desc: '신발',
    color: '2개 색상',
    price: 239000,
    discount: 0.35,
    condition: '',
    type01: 'men',
    type02: 'snkrs',
    type03: 'retro',
  },
  {
    id: 'pro_08',
    image: process.env.PUBLIC_URL+'/images/8.jpg',
    title: '조던 Why Not?',
    desc: '남성 팬츠',
    color: '1개 색상',
    price: 99000,
    discount: 0,
    condition: '',
    type01: 'men',
    type02: 'pants',
  },
  {
    id: 'pro_09',
    image: process.env.PUBLIC_URL+'/images/9.jpg',
    title: '조던 에센셜',
    desc: '남성 스테이트먼트 플리스 팬츠',
    color: '5개 색상',
    price: 105000,
    discount: 0,
    condition: '신상품',
    type01: 'men',
    type02: 'pants',
  },
  {
    id: 'pro_10',
    image: process.env.PUBLIC_URL+'/images/10.jpg',
    title: '에어 조던 1 미드',
    desc: '주니어 신발',
    color: '1개 색상',
    price: 129000,
    discount: 0.2,
    condition: '',
    type01: 'junior',
    type02: 'snkrs',
  },
  {
    id: 'pro_11',
    image: process.env.PUBLIC_URL+'/images/11.jpg',
    title: '루카 1 PF',
    desc: '남성 농구화',
    color: '4개 색상',
    price: 129000,
    discount: 0,
    condition: '',
    type01: 'men',
    type02: 'snkrs',
  },
  {
    id: 'pro_12',
    image: process.env.PUBLIC_URL+'/images/12.jpg',
    title: '에어 조던 1 로우 SE',
    desc: '여성 신발',
    color: '2개 색상',
    price: 139000,
    discount: 0,
    condition: '신상품',
    type01: 'women',
    type02: 'snkrs',
  },
  {
    id: 'pro_13',
    image: process.env.PUBLIC_URL+'/images/12.jpg',
    title: '조던 23 엔지니어드',
    desc: '남성 플리스 팬츠',
    color: '1개 색상',
    price: 139000,
    discount: 0,
    condition: '친환경 소재',
    type01: 'men',
    type02: 'pants',
  },
  {
    id: 'pro_14',
    image: process.env.PUBLIC_URL+'/images/14.jpg',
    title: '에어 조던 1 줌 컴포트 2',
    desc: '남성 신발',
    color: '1개 색상',
    price: 179000,
    discount: 0,
    condition: '신상품',
    type01: 'men',
    type02: 'snkrs',
  },
  {
    id: 'pro_15',
    image: process.env.PUBLIC_URL+'/images/15.jpg',
    title: '에어 조던 1 줌 Cmft',
    desc: '신발',
    color: '3개 색상',
    price: 169000,
    discount: 0.1,
    condition: '',
    type01: 'men',
    type02: 'snkrs',
  },
  {
    id: 'pro_16',
    image: process.env.PUBLIC_URL+'/images/16.jpg',
    title: '에어 조던 3 레트로',
    desc: '남성 신발',
    color: '1개 색상',
    price: 239000,
    discount: 0.15,
    condition: '',
    type01: 'men',
    type02: 'snkrs',
    type03: 'retro',
  },
  {
    id: 'pro_17',
    image: process.env.PUBLIC_URL+'/images/17.jpg',
    title: '에어 조던 1 로우 SE',
    desc: '여성 신발',
    color: '1개 색상',
    price: 139000,
    discount: 0.15,
    condition: '',
    type01: 'women',
    type02: 'snkrs',
  },
  {
    id: 'pro_18',
    image: process.env.PUBLIC_URL+'/images/18.jpg',
    title: '에어 조던 5 레트로 로우 PSG',
    desc: '남성 신발 ',
    color: '1개 색상',
    price: 239000,
    discount: 0.2,
    condition: '',
    type01: 'men',
    type02: 'snkrs',
    type03: 'retro',
  },
  {
    id: 'pro_19',
    image: process.env.PUBLIC_URL+'/images/19.jpg',
    title: '에어 조던 7 레트로 SE',
    desc: '남성 신발',
    color: '1개 색상',
    price: 249000,
    discount: 0.35,
    condition: '',
    type01: 'men',
    type02: 'snkrs',
    type03: 'retro',
  },
  {
    id: 'pro_20',
    image: process.env.PUBLIC_URL+'/images/20.jpg',
    title: '에어 조던 XXXVII 로우 PF',
    desc: '남성 농구화',
    color: '1개 색상',
    price: 209000,
    discount: 0,
    condition: '신상품',
    type01: 'men',
    type02: 'snkrs',
  },
  {
    id: 'pro_21',
    image: process.env.PUBLIC_URL+'/images/21.jpg',
    title: '조던 에센셜',
    desc: '남성 플리스 윈터 팬츠',
    color: '1개 색상',
    price: 85000,
    discount: 0,
    condition: '친환경 소재',
    type01: 'men',
    type02: 'pants',
  },
  {
    id: 'pro_22',
    image: process.env.PUBLIC_URL+'/images/22.jpg',
    title: '조던 스포츠',
    desc: '남성 바시티 재킷',
    color: '1개 색상',
    price: 149000,
    discount: 0,
    condition: '',
    type01: 'men',
    type02: 'jaket',
  },
  {
    id: 'pro_23',
    image: process.env.PUBLIC_URL+'/images/23.jpg',
    title: '에어 조던 7 레트로',
    desc: '남성 신발',
    color: '1개 색상',
    price: 249000,
    discount: 0.3,
    condition: '',
    type01: 'men',
    type02: 'snkrs',
    type03: 'retro',
  },
  {
    id: 'pro_24',
    image: process.env.PUBLIC_URL+'/images/24.jpg',
    title: '조던 에센셜',
    desc: '남성 플리스 풀오버 후디',
    color: '4개 색상',
    price: 85000,
    discount: 0.2,
    condition: '',
    type01: 'men',
    type02: 'top',
  },
  {
    id: 'pro_25',
    image: process.env.PUBLIC_URL+'/images/25.jpg',
    title: '조던 에센셜',
    desc: '남성 플리스 팬츠',
    color: '3개 색상',
    price: 85000,
    discount: 0.1,
    condition: '',
    type01: 'men',
    type02: 'pants',
  },
  {
    id: 'pro_26',
    image: process.env.PUBLIC_URL+'/images/26.jpg',
    title: '에어 조던 1 로우',
    desc: '여성 신발',
    color: '1개 색상',
    price: 129000,
    discount: 0,
    condition: '',
    type01: 'women',
    type02: 'snkrs',
  },
  {
    id: 'pro_27',
    image: process.env.PUBLIC_URL+'/images/27.jpg',
    title: '조던 에센셜',
    desc: '여성 유틸리티 팬츠',
    color: '1개 색상',
    price: 119000,
    discount: 0.35,
    condition: '신상품',
    type01: 'women',
    type02: 'pants',
  },
  {
    id: 'pro_28',
    image: process.env.PUBLIC_URL+'/images/28.jpg',
    title: '에어 조던 5 레트로',
    desc: '남성 신발',
    color: '1개 색상',
    price: 239000,
    discount: 0.15,
    condition: '',
    type01: 'men',
    type02: 'snkrs',
    type03: 'retro',
  },
  {
    id: 'pro_29',
    image: process.env.PUBLIC_URL+'/images/29.jpg',
    title: '에어 조던 1 애클러메이트',
    desc: '여성 신발',
    color: '1개 색상',
    price: 179000,
    discount: 0,
    condition: '',
    type01: 'women',
    type02: 'snkrs',
  },
  {
    id: 'pro_30',
    image: process.env.PUBLIC_URL+'/images/30.jpg',
    title: '조던 플라이트 MVP',
    desc: '남성 플라이트 MVP',
    color: '2개 색상',
    price: 85000,
    discount: 0,
    condition: '',
    type01: 'men',
    type02: 'pants',
  },
  {
    id: 'pro_31',
    image: process.env.PUBLIC_URL+'/images/31.jpg',
    title: '에어 조던 1 줌 에어 컴포트',
    desc: '여성 신발',
    color: '1개 색상',
    price: 169000,
    discount: 0.2,
    condition: '',
    type01: 'women',
    type02: 'snkrs',
  },
  {
    id: 'pro_32',
    image: process.env.PUBLIC_URL+'/images/32.jpg',
    title: "조던 .5 'Why Not ",
    desc: '남성 농구화',
    color: '1개 색상',
    price: 159000,
    discount: 0.35,
    condition: '',
    type01: 'men',
    type02: 'snkrs',
  },
  {
    id: 'pro_33',
    image: process.env.PUBLIC_URL+'/images/33.jpg',
    title: '조던 플라이트',
    desc: '여성 패딩 재킷',
    color: '1개 색상',
    price: 219000,
    discount: 0,
    condition: '',
    type01: 'women',
    type02: 'jacket',
  },
  {
    id: 'pro_34',
    image: process.env.PUBLIC_URL+'/images/34.jpg',
    title: '조던',
    desc: '에브리데이 크루 삭스(3켤레)',
    color: '2개 색상',
    price: 22000,
    discount: 0,
    condition: '신상품',
    type01: 'genderless',
    type02: 'goods',
  },
  {
    id: 'pro_35',
    image: process.env.PUBLIC_URL+'/images/35.jpg',
    title: '조던 플라이트',
    desc: '여성 자카드 니트 카디건',
    color: '1개 색상',
    price: 139000,
    discount: 0,
    condition: '신상품',
    type01: 'women',
    type02: 'jacket',
  },
  {
    id: 'pro_36',
    image: process.env.PUBLIC_URL+'/images/36.jpg',
    title: '조던 브루클린',
    desc: '여성 플리스 팬츠',
    color: '2개 색상',
    price: 85000,
    discount: 0.2,
    condition: '',
    type01: 'women',
    type02: 'pants',
  },
  {
    id: 'pro_37',
    image: process.env.PUBLIC_URL+'/images/37.jpg',
    title: '조던 x Off-White',
    desc: '남성 숏슬리프 탑',
    color: '1개 색상',
    price: 149000,
    discount: 0,
    condition: '',
    type01: 'men',
    type02: 'top',
  },
  {
    id: 'pro_38',
    image: process.env.PUBLIC_URL+'/images/38.jpg',
    title: '조던 1 로우 알트',
    desc: '베이비 신발',
    color: '2개 색상',
    price: 69000,
    discount: 0,
    condition: '',
    type01: 'baby',
    type02: 'snkrs',
  },
  {
    id: 'pro_39',
    image: process.env.PUBLIC_URL+'/images/39.jpg',
    title: '스카이 조던 1',
    desc: '리틀키즈 신발',
    color: '1개 색상',
    price: 89000,
    discount: 0,
    condition: '',
    type01: 'kids',
    type02: 'snkrs',
  },
  {
    id: 'pro_40',
    image: process.env.PUBLIC_URL+'/images/40.jpg',
    title: '에어 조던 5 레트로 GTX',
    desc: '여성 신발',
    color: '1개 색상',
    price: 259000,
    discount: 0.2,
    condition: '',
    type01: 'women',
    type02: 'snkrs',
    type03: 'retro',
  },
  {
    id: 'pro_41',
    image: process.env.PUBLIC_URL+'/images/41.jpg',
    title: '조던 23 엔지니어드',
    desc: '남성 플리스 풀오버',
    color: '2개 색상',
    price: 169000,
    discount: 0,
    condition: '친환경 소재',
    type01: 'men',
    type02: 'top',
  },
  {
    id: 'pro_42',
    image: process.env.PUBLIC_URL+'/images/42.jpg',
    title: '조던 스포츠 드라이 핏',
    desc: '남성 3/4 타이츠',
    color: '1개 색상',
    price: 49000,
    discount: 0,
    condition: '',
    type01: 'men',
    type02: 'pants',
  },
  {
    id: 'pro_43',
    image: process.env.PUBLIC_URL+'/images/43.jpg',
    title: '조던 에센셜',
    desc: '남성 웜업 재킷',
    color: '2개 색상',
    price: 139000,
    discount: 0,
    condition: '신상품',
    type01: 'men',
    type02: 'top',
  },
  {
    id: 'pro_44',
    image: process.env.PUBLIC_URL+'/images/44.jpg',
    title: '조던 플라이트 에센셜',
    desc: '남성용 오버사이즈 티셔츠',
    color: '2개 색상',
    price: 55000,
    discount: 0,
    condition: '',
    type01: 'men',
    type02: 'top',
  },
  {
    id: 'pro_45',
    image: process.env.PUBLIC_URL+'/images/45.jpg',
    title: '조던 에센셜',
    desc: '남성 레니게이드 재킷',
    color: '1개 색상',
    price: 289000,
    discount: 0,
    condition: '신상품',
    type01: 'men',
    type02: 'jacket',
  },
  {
    id: 'pro_46',
    image: process.env.PUBLIC_URL+'/images/46.jpg',
    title: '조던 점프맨',
    desc: '여성 미디엄 서포트 일체형 패드 스포츠 브라',
    color: '1개 색상',
    price: 45000,
    discount: 0.2,
    condition: '친환경 소재',
    type01: 'women',
    type02: 'top',
  },
  {
    id: 'pro_47',
    image: process.env.PUBLIC_URL+'/images/47.jpg',
    title: '조던 에센셜',
    desc: '남성 스테이트먼트 바시티 재킷',
    color: '2개 색상',
    price: 279000,
    discount: 0.3,
    condition: '',
    type01: 'men',
    type02: 'jacket',
  },
  {
    id: 'pro_48',
    image: process.env.PUBLIC_URL+'/images/48.jpg',
    title: '조던 플라이트',
    desc: '여성 벨루어 팬츠',
    color: '1개 색상',
    price: 109000,
    discount: 0,
    condition: '',
    type01: 'women',
    type02: 'pants',
  },
  {
    id: 'pro_49',
    image: process.env.PUBLIC_URL+'/images/49.jpg',
    title: '조던',
    desc: '여성 우븐 팬츠',
    color: '1개 색상',
    price: 95000,
    discount: 0.3,
    condition: '',
    type01: 'women',
    type02: 'pants',
  },
  {
    id: 'pro_50',
    image: process.env.PUBLIC_URL+'/images/50.jpg',
    title: '에어 조던 1 로우 SE',
    desc: '주니어 신발',
    color: '1개 색상',
    price: 139000,
    discount: 0,
    condition: '',
    type01: 'junior',
    type02: 'snkrs',
  },
  {
    id: 'pro_51',
    image: process.env.PUBLIC_URL+'/images/51.jpg',
    title: '조던 소피아',
    desc: '여성 슬라이드',
    color: '3개 색상',
    price: 99000,
    discount: 0,
    condition: '',
    type01: 'women',
    type02: 'snkrs',
  },
  {
    id: 'pro_52',
    image: process.env.PUBLIC_URL+'/images/52.jpg',
    title: '조던 드라이 핏 스포츠 BC',
    desc: '남성 다이아몬드 쇼츠',
    color: '1개 색상',
    price: 65000,
    discount: 0.35,
    condition: '친환경 소재',
    type01: 'men',
    type02: 'pants',
  },
  {
    id: 'pro_53',
    image: process.env.PUBLIC_URL+'/images/53.jpg',
    title: '조던 시리즈 미드',
    desc: '남성 신발',
    color: '2개 색상',
    price: 109000,
    discount: 0,
    condition: '',
    type01: 'men',
    type02: 'snkrs',
  },
  {
    id: 'pro_54',
    image: process.env.PUBLIC_URL+'/images/54.jpg',
    title: '루카 1 PF',
    desc: '남성 농구화',
    color: '1개 색상',
    price: 129000,
    discount: 0,
    condition: '',
    type01: 'men',
    type02: 'snkrs',
  },
  {
    id: 'pro_55',
    image: process.env.PUBLIC_URL+'/images/55.jpg',
    title: '에어 조던 1 로우',
    desc: '주니어 신발',
    color: '2개 색상',
    price: 109000,
    discount: 0.15,
    condition: '',
    type01: 'junior',
    type02: 'snkrs',
  },
  {
    id: 'pro_56',
    image: process.env.PUBLIC_URL+'/images/56.jpg',
    title: '조던 3 레트로',
    desc: '리틀키즈 신발',
    color: '1개 색상',
    price: 119000,
    discount: 0.2,
    condition: '',
    type01: 'kids',
    type02: 'snkrs',
    type03: 'retro',
  },
  {
    id: 'pro_57',
    image: process.env.PUBLIC_URL+'/images/57.jpg',
    title: '조던 점프맨 클래식99 메탈',
    desc: '캡',
    color: '1개 색상',
    price: 33000,
    discount: 0,
    condition: '',
    type01: 'genderless',
    type02: 'goods',
  },
  {
    id: 'pro_58',
    image: process.env.PUBLIC_URL+'/images/58.jpg',
    title: '에어 조던 4 레트로 SE',
    desc: '남성 신발',
    color: '1개 색상',
    price: 249000,
    discount: 0.15,
    condition: '',
    type01: 'men',
    type02: 'snkrs',
    type03: 'retro',
  },
  {
    id: 'pro_59',
    image: process.env.PUBLIC_URL+'/images/59.jpg',
    title: '에어 조던 XXXVII PF',
    desc: '남성 농구화',
    color: '2개 색상',
    price: 219000,
    discount: 0.2,
    condition: '',
    type01: 'men',
    type02: 'snkrs',
  },
  {
    id: 'pro_60',
    image: process.env.PUBLIC_URL+'/images/60.jpg',
    title: '조던 플라이트 시카고',
    desc: '여성 팬츠',
    color: '2개 색상',
    price: 149000,
    discount: 0,
    condition: '',
    type01: 'women',
    type02: 'pants',
  },
  {
    id: 'pro_61',
    image: process.env.PUBLIC_URL+'/images/61.jpg',
    title: '조던 원 테이크 4 PF',
    desc: '남성 신발',
    color: '2개 색상',
    price: 119000,
    discount: 0,
    condition: '',
    type01: 'men',
    type02: 'snkrs',
  },
  {
    id: 'pro_62',
    image: process.env.PUBLIC_URL+'/images/62.jpg',
    title: '조던 드라이 핏 스포츠',
    desc: '남성 팬츠',
    color: '2개 색상',
    price: 105000,
    discount: 0,
    condition: '신상품',
    type01: 'men',
    type02: 'pants',
  },
  {
    id: 'pro_63',
    image: process.env.PUBLIC_URL+'/images/63.jpg',
    title: '자이언 2 PF',
    desc: '남성 농구화',
    color: '3개 색상',
    price: 139000,
    discount: 0.3,
    condition: '',
    type01: 'men',
    type02: 'snkrs',
  },
  {
    id: 'pro_64',
    image: process.env.PUBLIC_URL+'/images/64.jpg',
    title: '자이언 2 PF',
    desc: '남성 농구화',
    color: '1개 색상',
    price: 159000,
    discount: 0.3,
    condition: '',
    type01: 'men',
    type02: 'snkrs',
  },
  {
    id: 'pro_65',
    image: process.env.PUBLIC_URL+'/images/65.jpg',
    title: '조던 에센셜',
    desc: '여성 티셔츠 드레스',
    color: '1개 색상',
    price: 69000,
    discount: 0.35,
    condition: '',
    type01: 'women',
    type02: 'top',
  },
  {
    id: 'pro_66',
    image: process.env.PUBLIC_URL+'/images/66.jpg',
    title: '조던 1 로우 알트 SE',
    desc: '베이비 신발',
    color: '1개 색상',
    price: 79000,
    discount: 0,
    condition: '신상품',
    type01: 'baby',
    type02: 'snkrs',
  },
  {
    id: 'pro_67',
    image: process.env.PUBLIC_URL+'/images/67.jpg',
    title: '조던 에센셜',
    desc: '남성 워밍업 팬츠',
    color: '1개 색상',
    price: 119000,
    discount: 0,
    condition: '친환경 소재',
    type01: 'men',
    type02: 'pants',
  },
  {
    id: 'pro_68',
    image: process.env.PUBLIC_URL+'/images/68.jpg',
    title: '조던 23/7',
    desc: '리틀키즈 신발',
    color: '2개 색상',
    price: 79000,
    discount: 0,
    condition: '',
    type01: 'kids',
    type02: 'snkrs',
  },
  {
    id: 'pro_69',
    image: process.env.PUBLIC_URL+'/images/69.jpg',
    title: '조던',
    desc: '에브리데이 노쇼 삭스(3켤레)',
    color: '1개 색상',
    price: 22000,
    discount: 0,
    condition: '신상품',
    type01: 'genderless',
    type02: 'goods',
  },
  {
    id: 'pro_70',
    image: process.env.PUBLIC_URL+'/images/70.jpg',
    title: '조던 23 엔지니어드',
    desc: '남성 재킷',
    color: '3개 색상',
    price: 129000,
    discount: 0.3,
    condition: '신상품',
    type01: 'men',
    type02: 'jacket',
  },
  {
    id: 'pro_71',
    image: process.env.PUBLIC_URL+'/images/71.jpg',
    title: '조던 에센셜 윈터',
    desc: '남성 플리스 후디',
    color: '2개 색상',
    price: 99000,
    discount: 0,
    condition: '친환경 소재',
    type01: 'men',
    type02: 'top',
  },
  {
    id: 'pro_72',
    image: process.env.PUBLIC_URL+'/images/72.jpg',
    title: '조던 플라이트',
    desc: '여성 탑',
    color: '2개 색상',
    price: 59000,
    discount: 0,
    condition: '',
    type01: 'women',
    type02: 'top',
  },
  {
    id: 'pro_73',
    image: process.env.PUBLIC_URL+'/images/73.jpg',
    title: '에어 조던 1 미드 SE',
    desc: '여성 신발',
    color: '1개 색상',
    price: 169000,
    discount: 0,
    condition: '친환경 소재',
    type01: 'women',
    type02: 'snkrs',
  },
  {
    id: 'pro_74',
    image: process.env.PUBLIC_URL+'/images/74.jpg',
    title: '에어 조던 1 로우 SE',
    desc: '주니어 신발',
    color: '1개 색상',
    price: 129000,
    discount: 0,
    condition: '',
    type01: 'junior',
    type02: 'snkrs',
  },
  {
    id: 'pro_75',
    image: process.env.PUBLIC_URL+'/images/75.jpg',
    title: '조던 에센셜',
    desc: '홀리데이 점프맨 플리스 풀오버',
    color: '2개 색상',
    price: 99000,
    discount: 0,
    condition: '',
    type01: 'men',
    type02: 'top',
  },
  {
    id: 'pro_76',
    image: process.env.PUBLIC_URL+'/images/76.jpg',
    title: '에어 조던 2 레트로 로우 타이탄',
    desc: '신발',
    color: '1개 색상',
    price: 269000,
    discount: 0.1,
    condition: '',
    type01: 'genderless',
    type02: 'snkrs',
    type03: 'retro',
  },
  {
    id: 'pro_77',
    image: process.env.PUBLIC_URL+'/images/77.jpg',
    title: '조던 점프맨 헤리티지86',
    desc: '워시드 캡',
    color: '2개 색상',
    price: 29000,
    discount: 0.15,
    condition: '',
    type01: 'genderless',
    type02: 'goods',
  },
  {
    id: 'pro_78',
    image: process.env.PUBLIC_URL+'/images/78.jpg',
    title: '조던 스포츠',
    desc: '여성 조거',
    color: '1개 색상',
    price: 85000,
    discount: 0.1,
    condition: '',
    type01: 'women',
    type02: 'pants',
  },
  {
    id: 'pro_79',
    image: process.env.PUBLIC_URL+'/images/79.jpg',
    title: '에어 조던 1 미드',
    desc: '여성 신발',
    color: '1개 색상',
    price: 159000,
    discount: 0,
    condition: '',
    type01: 'women',
    type02: 'snkrs',
  },
  {
    id: 'pro_80',
    image: process.env.PUBLIC_URL+'/images/80.jpg',
    title: '에어 조던 1 미드 SE',
    desc: '여성 신발',
    color: '1개 색상',
    price: 159000,
    discount: 0.15,
    condition: '',
    type01: 'women',
    type02: 'snkrs',
  },
  {
    id: 'pro_81',
    image: process.env.PUBLIC_URL+'/images/81.jpg',
    title: '점프맨 투 트레이',
    desc: '남성 신발',
    color: '4개 색상',
    price: 179000,
    discount: 0.1,
    condition: '',
    type01: 'men',
    type02: 'snkrs',
  },
  {
    id: 'pro_82',
    image: process.env.PUBLIC_URL+'/images/82.jpg',
    title: '에어 조던 1 미드 SE',
    desc: '여성 신발',
    color: '1개 색상',
    price: 159000,
    discount: 0,
    condition: '친환경 소재',
    type01: 'women',
    type02: 'snkrs',
  },
  {
    id: 'pro_83',
    image: process.env.PUBLIC_URL+'/images/83.jpg',
    title: '조던 에센셜',
    desc: '남성 우븐 팬츠',
    color: '2개 색상',
    price: 89000,
    discount: 0,
    condition: '',
    type01: 'men',
    type02: 'pants',
  },
  {
    id: 'pro_84',
    image: process.env.PUBLIC_URL+'/images/84.jpg',
    title: '조던 플라이트',
    desc: '여성 벨루어 재킷',
    color: '2개 색상',
    price: 129000,
    discount: 0,
    condition: '',
    type01: 'women',
    type02: 'top',
  },
  {
    id: 'pro_85',
    image: process.env.PUBLIC_URL+'/images/85.jpg',
    title: '조던',
    desc: '유틸리티 비니',
    color: '1개 색상',
    price: 35000,
    discount: 0,
    condition: '',
    type01: 'genderless',
    type02: 'goods',
  },
  {
    id: 'pro_86',
    image: process.env.PUBLIC_URL+'/images/86.jpg',
    title: '조던 플라이트 헤리티지 85',
    desc: '남성 티셔츠',
    color: '1개 색상',
    price: 55000,
    discount: 0.35,
    condition: '',
    type01: 'men',
    type02: 'top',
  },
  {
    id: 'pro_87',
    image: process.env.PUBLIC_URL+'/images/87.jpg',
    title: '조던 맥스 아우라 4',
    desc: '남성 신발',
    color: '2개 색상',
    price: 149000,
    discount: 0.2,
    condition: '',
    type01: 'men',
    type02: 'snkrs',
  },
  {
    id: 'pro_88',
    image: process.env.PUBLIC_URL+'/images/88.jpg',
    title: '조던 스테이트먼트 에센셜',
    desc: '남성 크롭 팬츠',
    color: '1개 색상',
    price: 99000,
    discount: 0.35,
    condition: '',
    type01: 'men',
    type02: 'pants',
  },
  {
    id: 'pro_89',
    image: process.env.PUBLIC_URL+'/images/89.jpg',
    title: '조던 플라이트',
    desc: '여성 플리스 팬츠',
    color: '4개 색상',
    price: 99000,
    discount: 0,
    condition: '',
    type01: 'women',
    type02: 'pants',
  },
  {
    id: 'pro_90',
    image: process.env.PUBLIC_URL+'/images/90.jpg',
    title: '브루클린 네츠 코트사이드 스테이트먼트 에디션',
    desc: '남성 조던 NBA 플리스 스웻셔츠',
    color: '1개 색상',
    price: 89000,
    discount: 0,
    condition: '',
    type01: 'men',
    type02: 'top',
  },
  {
    id: 'pro_91',
    image: process.env.PUBLIC_URL+'/images/92.jpg',
    title: '조던 플라이트 헤리티지',
    desc: '남성 후디',
    color: '2개 색상',
    price: 169000,
    discount: 0,
    condition: '',
    type01: 'men',
    type02: 'top',
  },
  {
    id: 'pro_92',
    image: process.env.PUBLIC_URL+'/images/92.jpg',
    title: '조던 델타 3 로우',
    desc: '주니어 신발',
    color: '3개 색상',
    price: 119000,
    discount: 0.25,
    condition: '',
    type01: 'junior',
    type02: 'snkrs',
  },
  {
    id: 'pro_93',
    image: process.env.PUBLIC_URL+'/images/93.jpg',
    title: '조던 에센셜',
    desc: '여성 박시 티셔츠',
    color: '2개 색상',
    price: 49000,
    discount: 0.15,
    condition: '친환경 소재',
    type01: 'women',
    type02: 'top',
  },
  {
    id: 'pro_94',
    image: process.env.PUBLIC_URL+'/images/94.jpg',
    title: '조던 프로 점프맨',
    desc: '스냅백 모자',
    color: '2개 색상',
    price: 33000,
    discount: 0,
    condition: '친환경 소재',
    type01: 'genderless',
    type02: 'goods',
  },
  {
    id: 'pro_95',
    image: process.env.PUBLIC_URL+'/images/95.jpg',
    title: '조던 에센셜 프린트 팬츠',
    desc: '리틀키즈 팬츠',
    color: '1개 색상',
    price: 59000,
    discount: 0,
    condition: '',
    type01: 'kids',
    type02: 'pants',
  },
  {
    id: 'pro_96',
    image: process.env.PUBLIC_URL+'/images/96.jpg',
    title: '에어 조던 XXXVI 로우 루카 PF',
    desc: '남성 농구화',
    color: '1개 색상',
    price: 209000,
    discount: 0.15,
    condition: '',
    type01: 'men',
    type02: 'snkrs',
  },
]

export default prodata